#!/usr/bin/env python3
"""
PRN Pattern Validation Script

Validates that the 247-byte PRN (Pseudo-Random Number) pattern in src/data.asm
matches the expected pattern generated by the formula:
    value = ((value * 17) + 137) & 0xFF
    seed = 0x42

The 247-byte length is intentionally prime-like (not 256-aligned) to detect
address bus faults like crossed lines, mirroring, and decode failures.

Credit: Methodology by Sven Petersen
"""

import sys
import re

# PRN pattern generation
def generate_prn_pattern(seed=0x42, length=247):
    """Generate PRN pattern using the formula from the implementation."""
    pattern = []
    value = seed

    for _ in range(length):
        # Generate next value first, then append (pattern doesn't include seed)
        value = ((value * 17) + 137) & 0xFF
        pattern.append(value)

    return pattern

# Parse data.asm to extract a labeled .byte table
def extract_table_from_asm(label, filename='src/data.asm'):
    """Extract the bytes of a labeled table from data.asm"""
    try:
        with open(filename, 'r') as f:
            content = f.read()

        # Find the labeled section (stops at the next blank line)
        pattern_match = re.search(
            label + r':.*?\.byte\s+(.*?)(?=\n\n|\.encoding|strAbout|$)',
            content,
            re.DOTALL
        )

        if not pattern_match:
            print(f"❌ Could not find {label} in data.asm")
            return None

        # Extract all .byte lines
        byte_lines = pattern_match.group(1)

        # Parse hex values
        hex_pattern = re.findall(r'\$([0-9a-fA-F]{2})', byte_lines)

        if not hex_pattern:
            print(f"❌ Could not parse hex bytes from {label}")
            return None

        # Convert to integers
        pattern = [int(h, 16) for h in hex_pattern]

        return pattern

    except FileNotFoundError:
        print(f"❌ File not found: {filename}")
        return None
    except Exception as e:
        print(f"❌ Error reading file: {e}")
        return None

def main():
    print("🔍 Validating PRN Pattern...")
    print()

    # Generate expected pattern
    print("📐 Generating expected PRN pattern...")
    print("   Formula: value = ((value * 17) + 137) & 0xFF")
    print("   Seed: 0x42")
    print("   Length: 247 bytes")
    expected = generate_prn_pattern()
    print(f"   ✓ Generated {len(expected)} bytes")
    print()

    # Extract actual pattern from data.asm
    print("📄 Extracting PrnTestPattern from src/data.asm...")
    actual = extract_table_from_asm('PrnTestPattern')

    if actual is None:
        sys.exit(1)

    print(f"   ✓ Found {len(actual)} bytes")
    print()

    # Validate length
    if len(actual) != 247:
        print(f"❌ Length mismatch: expected 247 bytes, got {len(actual)} bytes")
        sys.exit(1)

    if len(actual) != len(expected):
        print(f"❌ Length mismatch: expected {len(expected)} bytes, got {len(actual)} bytes")
        sys.exit(1)

    # Compare byte-by-byte
    print("🔬 Comparing patterns byte-by-byte...")
    mismatches = []

    for i, (exp, act) in enumerate(zip(expected, actual)):
        if exp != act:
            mismatches.append((i, exp, act))

    if mismatches:
        print(f"❌ Found {len(mismatches)} mismatches:")
        print()
        for i, exp, act in mismatches[:10]:  # Show first 10
            print(f"   Byte {i:3d}: expected ${exp:02X}, got ${act:02X}")

        if len(mismatches) > 10:
            print(f"   ... and {len(mismatches) - 10} more")

        print()
        print("❌ PRN pattern validation FAILED")
        sys.exit(1)

    # Success
    print("   ✓ All 247 bytes match!")
    print()

    # Validate the extension table used by memBankTest's staggered per-page
    # reads: it must repeat the first 14 bytes of the pattern and sit right
    # after it, so PrnTestPattern+base,x (base 0-14, x 0-246) stays in bounds.
    print("📄 Extracting PrnTestPatternExt from src/data.asm...")
    extension = extract_table_from_asm('PrnTestPatternExt')

    if extension is None:
        sys.exit(1)

    if len(extension) != 14:
        print(f"❌ Extension length mismatch: expected 14 bytes, got {len(extension)}")
        sys.exit(1)

    if extension != expected[:14]:
        print("❌ PrnTestPatternExt does not repeat the first 14 PRN bytes")
        sys.exit(1)

    print("   ✓ Extension repeats the first 14 PRN bytes")
    print()
    print("✅ PRN pattern validation PASSED")
    print()
    print("Pattern integrity verified:")
    print("  - Correct 247-byte length (prime-like, non-256-aligned)")
    print("  - Matches generated pattern from formula")
    print("  - Ready for address bus fault detection")
    sys.exit(0)

if __name__ == '__main__':
    main()
